_target_: src.models.regression.ngboost.NGBoostModel

distribution: lognormal

n_estimators: 1086
learning_rate: 0.0050383885532647955

base_max_depth: 8
base_min_samples_leaf: 95
base_min_samples_split: 42

minibatch_frac: 0.7737028464682613
col_sample: 1.0

natural_gradient: true

random_state: 42
verbose: false
early_stopping_rounds: 50