_target_: src.data.dataset.Dataset

# data_dir: data/processed/splits
# data_dir: data/processed/splits_rolling_features
data_dir: data/processed/splits_gust_excess

# target: has_gust
target: gust_excess_ms

feature_columns: ${features.columns}

metadata_columns:
  - station_id
  - icao
  - station_name
  - run_time
  - valid_time
  - lead_time