defaults:
  - model: logistic_regression
  - dataset: default
  - trainer: default
  - evaluation: classification
  - features: arome
  - wandb: default
  - paths: default
  - _self_

task: classification
# target: has_gust
target: gust_excess_ms 
seed: 42

experiment_name: ${hydra:runtime.choices.model}